version: "3.2"
services:
  fhe-api:
    build:
        context: ./
        dockerfile: ./Dockerfile
    image: fhe-api:v1.1
    ports:
        - "5000:5000"
    environment:
        - EVAL_KEY_PATH=.
        - DATABASE_URL=
        - USE_OAUTH2=0

        